name: Weekly Cricket Data Scraper

on:
  push:
    branches:
      - main # or your default branch name

  schedule:
    # Runs at 11:00 AM UTC on Thursdays
    - cron: "0 11 * * 4"

    # Runs at 6:00 AM UTC on Fridays
    - cron: "0 6 * * 5"

    # Runs at 11:00 AM UTC on Fridays
    - cron: "0 11 * * 5"

  workflow_dispatch: # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Get Chrome Version
        run: |
          echo "CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)" >> $GITHUB_ENV

      - name: Find Matching ChromeDriver Version
        run: |
          CHROME_DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" \
          | jq -r --arg v "$CHROME_VERSION" '.channels.Stable.versions[] | select(.version | startswith($v)) | .version' | head -n 1)
          echo "CHROME_DRIVER_VERSION=$CHROME_DRIVER_VERSION" >> $GITHUB_ENV

      - name: Install ChromeDriver
        run: |
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_DRIVER_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          chmod +x /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary selenium beautifulsoup4 webdriver-manager

      - name: Run scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python main.py
